name: Deploy K8S

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      run: |
        curl https://sdk.cloud.google.com | bash > /dev/null
        source $HOME/google-cloud-sdk/path.bash.inc
        gcloud components update kubectl

    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" | jq . > $HOME/service-account.json
        gcloud auth activate-service-account --key-file=$HOME/service-account.json
        gcloud config set project multi-k8s-451513
        gcloud config set compute/zone europe-central2-b
        gcloud container clusters get-credentials multi-cluster

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" -password-stdin

    - name: Docker build image
      run: docker build -t etenity/react-test -f .client/Dockerfile.dev ./client

    - name: Docker execute
      run: docker run -e CI=true etenity/react-test npm test
